### ISSUE TITLE
About the implementation

### ISSUE THREAD

**Issue by coldmanck** [HimariO/PyTorch-ERNIE-Vil#1]
Hi @HimariO do you plan to release your PyTorch implementation of ERNIE-Vil? Thanks!

**Comment by HimariO** [comment]
Hi @coldmanck the actual implementation is already included in the [hateful memes](https://github.com/HimariO/HatefulMemesChallenge/tree/main/ERNIE-Vil) repo. I just don't find the time to improve the original training config framework and migrate the code to this repo.  The implementation for the hateful memes challenge is totally usable if don't mind dealing with the janky config system from official implementation.
